name: Generate Image Gallery

on:
  push:
    branches:
      - main/Bilder/PostPictures  # Modify this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: List Images
      id: list_images
      run: |
        echo "::set-output name=images::$(ls -1 images/*.jpg images/*.jpeg images/*.png images/*.gif 2>/dev/null || true)"

    - name: Create HTML
      run: |
        echo "<!DOCTYPE html><html><head><title>Image Gallery</title></head><body><h1>My Image Gallery</h1><div id='imageGallery'>" > gallery.html
        for file in ${{ steps.list_images.outputs.images }}; do
          echo "<img src='${file}' alt='${file}' />" >> gallery.html
        done
        echo "</div></body></html>" >> gallery.html

    - name: Commit HTML
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add gallery.html
        git commit -m 'Auto-generate image gallery'
        git push

